### Token Assessment
POST http://localhost:8080/api/v1/google-evaluate
Content-Type: application/json

{
  "token": "",
  "siteKey": "abcd1234",
  "projectId": "ghij5678"
}


### Employee Data
GET http://localhost:8080/api/v1/employees


### NBA Teams Data
GET http://localhost:8080/api/v1/nba-teams

### Cities Data
GET http://localhost:8080/api/v1/cities

### Countries Data
GET http://localhost:8080/api/v1/countries

### Inventory Data
GET http://localhost:8080/api/v1/inventory
